
[window]
dimensions = { columns = 82, lines= 52 }
padding = { x= 5, y= 5 }
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
opacity = 0.7

[scrolling]
history = 5000
multiplier = 3

[font]
normal = { family = "Source Code Pro", style = "Regular" }
bold = { family = "Source Code Pro", style = "Bold" }
italic = { family = "Source Code Pro", style = "Italic" }
bold_italic = { family = "Source Code Pro", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 1 }

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "F11", mods = "None", action = "ToggleFullscreen" },
    { key = "Paste", mods = "None", action = "Paste" },
    { key = "Copy", mods = "None", action = "Copy" },
    # { key = "L", mods = "Control", action = "ClearLogNotice" },
    # { key = "L", mods = "Control", chars = "\x0c" },
    { key = "PageUp", mods = "None", action = "ScrollPageUp", mode = "Alt"},
    { key = "PageDown", mods = "None", action = "ScrollPageDown", mode = "Alt" },
    { key = "Home", mods = "Shift", action = "ScrollToTop", mode = "Alt" },
    { key = "End", mods = "Shift", action = "ScrollToBottom", mode = "Alt" },
]

[general]
import = [
  # "~/.config/alacritty/themes/nord.toml",
  "~/.config/alacritty/themes/dracula.toml",
  # "~/.config/alacritty/themes/doom_one.toml",
  # "~/.config/alacritty/themes/palenight.toml",
  # "~/.config/alacritty/themes/hardhacker.toml",
  # "~/.config/alacritty/themes/monokai_pro.toml",
  # "~/.config/alacritty/themes/tokyo-night.toml",
  # "~/.config/alacritty/themes/catppuccin_frappe.toml",
  # "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml",
]
